//
// File generated by core/utils/src/rootcint_tmp at Mon Apr 13 13:49:35 2015

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "G__MemstatGui.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::TMemStatDrawDlg TMemStatDrawDlg;
      #else
      class TMemStatDrawDlg  {
         public:
         //friend XX;
         // To force the creation of a virtual table, throw just in case.
         virtual ~TMemStatDrawDlg() throw() {};
         ::TQObjSender fQObject; //
         ::TMemStat* fMemStat; //
         ::TGComboBox* fboxOrder; //
         ::TGComboBox* fboxSortStat; //
         ::TGComboBox* fboxSortStamp; //
         ::TGNumberEntry* fNmbStackDeep; //
         ::TGNumberEntry* fNmbSortDeep; //
         ::TGNumberEntry* fNmbMaxLength; //
         ::TRootEmbeddedCanvas* fEc; //
      };
      #endif

   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void TMemStatViewerGUI_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void *new_TMemStatViewerGUI(void *p = 0);
   static void *newArray_TMemStatViewerGUI(Long_t size, void *p);
   static void delete_TMemStatViewerGUI(void *p);
   static void deleteArray_TMemStatViewerGUI(void *p);
   static void destruct_TMemStatViewerGUI(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TMemStatViewerGUI*)
   {
      ::TMemStatViewerGUI *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TMemStatViewerGUI >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TMemStatViewerGUI", ::TMemStatViewerGUI::Class_Version(), "include/TMemStatViewerGUI.h", 36,
                  typeid(::TMemStatViewerGUI), DefineBehavior(ptr, ptr),
                  &::TMemStatViewerGUI::Dictionary, isa_proxy, 4,
                  sizeof(::TMemStatViewerGUI) );
      instance.SetNew(&new_TMemStatViewerGUI);
      instance.SetNewArray(&newArray_TMemStatViewerGUI);
      instance.SetDelete(&delete_TMemStatViewerGUI);
      instance.SetDeleteArray(&deleteArray_TMemStatViewerGUI);
      instance.SetDestructor(&destruct_TMemStatViewerGUI);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TMemStatViewerGUI*)
   {
      return GenerateInitInstanceLocal((::TMemStatViewerGUI*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TMemStatViewerGUI*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

namespace ROOT {
   void TMemStatDrawDlg_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void TMemStatDrawDlg_Dictionary();
   static void delete_TMemStatDrawDlg(void *p);
   static void deleteArray_TMemStatDrawDlg(void *p);
   static void destruct_TMemStatDrawDlg(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TMemStatDrawDlg*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::TMemStatDrawDlg) == sizeof(::ROOT::Shadow::TMemStatDrawDlg));
      ::TMemStatDrawDlg *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::TMemStatDrawDlg),0);
      static ::ROOT::TGenericClassInfo 
         instance("TMemStatDrawDlg", "include/TMemStatDrawDlg.h", 34,
                  typeid(::TMemStatDrawDlg), DefineBehavior(ptr, ptr),
                  (void*)&TMemStatDrawDlg_ShowMembers, &TMemStatDrawDlg_Dictionary, isa_proxy, 4,
                  sizeof(::TMemStatDrawDlg) );
      instance.SetDelete(&delete_TMemStatDrawDlg);
      instance.SetDeleteArray(&deleteArray_TMemStatDrawDlg);
      instance.SetDestructor(&destruct_TMemStatDrawDlg);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TMemStatDrawDlg*)
   {
      return GenerateInitInstanceLocal((::TMemStatDrawDlg*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TMemStatDrawDlg*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void TMemStatDrawDlg_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::TMemStatDrawDlg*)0x0)->GetClass();
   }

} // end of namespace ROOT

//______________________________________________________________________________
TClass *TMemStatViewerGUI::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TMemStatViewerGUI::Class_Name()
{
   return "TMemStatViewerGUI";
}

//______________________________________________________________________________
const char *TMemStatViewerGUI::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TMemStatViewerGUI*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TMemStatViewerGUI::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TMemStatViewerGUI*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TMemStatViewerGUI::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TMemStatViewerGUI*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TMemStatViewerGUI::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TMemStatViewerGUI*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void TMemStatViewerGUI::Streamer(TBuffer &R__b)
{
   // Stream an object of class TMemStatViewerGUI.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(TMemStatViewerGUI::Class(),this);
   } else {
      R__b.WriteClassBuffer(TMemStatViewerGUI::Class(),this);
   }
}

//______________________________________________________________________________
void TMemStatViewerGUI::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class TMemStatViewerGUI.
      TClass *R__cl = ::TMemStatViewerGUI::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "*fViewer", &fViewer);
      R__insp.Inspect(R__cl, R__parent, "*fText", &fText);
      R__insp.Inspect(R__cl, R__parent, "*fNmbStackDeep", &fNmbStackDeep);
      R__insp.Inspect(R__cl, R__parent, "*fNmbSortDeep", &fNmbSortDeep);
      R__insp.Inspect(R__cl, R__parent, "fCurLib", (void*)&fCurLib);
      ::ROOT::GenericShowMembers("string", (void*)&fCurLib, R__insp, strcat(R__parent,"fCurLib."),false);
      R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "fCurFunc", (void*)&fCurFunc);
      ::ROOT::GenericShowMembers("string", (void*)&fCurFunc, R__insp, strcat(R__parent,"fCurFunc."),false);
      R__parent[R__ncp] = 0;
      TGCompositeFrame::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_TMemStatViewerGUI(void *p) {
      return  p ? new(p) ::TMemStatViewerGUI : new ::TMemStatViewerGUI;
   }
   static void *newArray_TMemStatViewerGUI(Long_t nElements, void *p) {
      return p ? new(p) ::TMemStatViewerGUI[nElements] : new ::TMemStatViewerGUI[nElements];
   }
   // Wrapper around operator delete
   static void delete_TMemStatViewerGUI(void *p) {
      delete ((::TMemStatViewerGUI*)p);
   }
   static void deleteArray_TMemStatViewerGUI(void *p) {
      delete [] ((::TMemStatViewerGUI*)p);
   }
   static void destruct_TMemStatViewerGUI(void *p) {
      typedef ::TMemStatViewerGUI current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::TMemStatViewerGUI

//______________________________________________________________________________
namespace ROOT {
   void TMemStatDrawDlg_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent)
   {
      // Inspect the data members of an object of class TMemStatDrawDlg.
      typedef ::ROOT::Shadow::TMemStatDrawDlg ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOT::GenerateInitInstanceLocal((const ::TMemStatDrawDlg*)0x0)->GetClass();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "fQObject", &sobj->fQObject);
      sobj->fQObject.ShowMembers(R__insp, strcat(R__parent,"fQObject.")); R__parent[R__ncp] = 0;
      R__insp.Inspect(R__cl, R__parent, "*fMemStat", &sobj->fMemStat);
      R__insp.Inspect(R__cl, R__parent, "*fboxOrder", &sobj->fboxOrder);
      R__insp.Inspect(R__cl, R__parent, "*fboxSortStat", &sobj->fboxSortStat);
      R__insp.Inspect(R__cl, R__parent, "*fboxSortStamp", &sobj->fboxSortStamp);
      R__insp.Inspect(R__cl, R__parent, "*fNmbStackDeep", &sobj->fNmbStackDeep);
      R__insp.Inspect(R__cl, R__parent, "*fNmbSortDeep", &sobj->fNmbSortDeep);
      R__insp.Inspect(R__cl, R__parent, "*fNmbMaxLength", &sobj->fNmbMaxLength);
      R__insp.Inspect(R__cl, R__parent, "*fEc", &sobj->fEc);
   }

}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_TMemStatDrawDlg(void *p) {
      delete ((::TMemStatDrawDlg*)p);
   }
   static void deleteArray_TMemStatDrawDlg(void *p) {
      delete [] ((::TMemStatDrawDlg*)p);
   }
   static void destruct_TMemStatDrawDlg(void *p) {
      typedef ::TMemStatDrawDlg current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::TMemStatDrawDlg

/********************************************************
* misc/memstat/src/G__MemstatGui.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableG__MemstatGui();

extern "C" void G__set_cpp_environmentG__MemstatGui() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("TMemStat.h");
  G__add_compiledheader("TMemStatViewerGUI.h");
  G__add_compiledheader("TMemStatDrawDlg.h");
  G__add_compiledheader("TMemStatResource.h");
  G__cpp_reset_tagtableG__MemstatGui();
}
#include <new>
extern "C" int G__cpp_dllrevG__MemstatGui() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TMemStatViewerGUI */
static int G__G__MemstatGui_277_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TMemStatViewerGUI* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TMemStatViewerGUI[n];
     } else {
       p = new((void*) gvp) TMemStatViewerGUI[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TMemStatViewerGUI;
     } else {
       p = new((void*) gvp) TMemStatViewerGUI;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__G__MemstatGuiLN_TMemStatViewerGUI));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_277_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TMemStatViewerGUI* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 4:
     //m: 4
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TMemStatViewerGUI(
(const TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (Option_t*) G__int(libp->para[3]));
     } else {
       p = new((void*) gvp) TMemStatViewerGUI(
(const TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]), (Option_t*) G__int(libp->para[3]));
     }
     break;
   case 3:
     //m: 3
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TMemStatViewerGUI(
(const TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]));
     } else {
       p = new((void*) gvp) TMemStatViewerGUI(
(const TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]));
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__G__MemstatGuiLN_TMemStatViewerGUI));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_277_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TMemStatViewerGUI::ShowGUI();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_277_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((TMemStatViewerGUI*) G__getstructoffset())->HandleButtonsSortStat((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((TMemStatViewerGUI*) G__getstructoffset())->HandleButtonsSortStat();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_277_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((TMemStatViewerGUI*) G__getstructoffset())->HandleButtonsSortStamp((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((TMemStatViewerGUI*) G__getstructoffset())->HandleButtonsSortStamp();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_277_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMemStatViewerGUI*) G__getstructoffset())->HandleDeep((Long_t) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_277_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMemStatViewerGUI*) G__getstructoffset())->HandleStampSelect((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_277_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMemStatViewerGUI*) G__getstructoffset())->HandleFuncSelect((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_277_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMemStatViewerGUI*) G__getstructoffset())->HandleLibSelect((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_277_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TMemStatViewerGUI::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_277_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TMemStatViewerGUI::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_277_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TMemStatViewerGUI::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_277_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TMemStatViewerGUI::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_277_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMemStatViewerGUI*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_277_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TMemStatViewerGUI::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_277_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TMemStatViewerGUI::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_277_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TMemStatViewerGUI::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_277_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TMemStatViewerGUI::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TMemStatViewerGUI G__TTMemStatViewerGUI;
static int G__G__MemstatGui_277_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TMemStatViewerGUI*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TMemStatViewerGUI*) (soff+(sizeof(TMemStatViewerGUI)*i)))->~G__TTMemStatViewerGUI();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TMemStatViewerGUI*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TMemStatViewerGUI*) (soff))->~G__TTMemStatViewerGUI();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* TMemStatDrawDlg */
static int G__G__MemstatGui_282_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const TMemStatDrawDlg*) G__getstructoffset())->GetListOfSignals());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_282_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((TMemStatDrawDlg*) G__getstructoffset())->Connect((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (void*) G__int(libp->para[2]), (const char*) G__int(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_282_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      G__letint(result7, 103, (long) ((TMemStatDrawDlg*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0]), (void*) G__int(libp->para[1])
, (const char*) G__int(libp->para[2])));
      break;
   case 2:
      G__letint(result7, 103, (long) ((TMemStatDrawDlg*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0]), (void*) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 103, (long) ((TMemStatDrawDlg*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0])));
      break;
   case 0:
      G__letint(result7, 103, (long) ((TMemStatDrawDlg*) G__getstructoffset())->Disconnect());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_282_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((TMemStatDrawDlg*) G__getstructoffset())->HighPriority((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((TMemStatDrawDlg*) G__getstructoffset())->HighPriority((const char*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_282_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((TMemStatDrawDlg*) G__getstructoffset())->LowPriority((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((TMemStatDrawDlg*) G__getstructoffset())->LowPriority((const char*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_282_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   G__va_arg_buf G__va_arg_bufobj;
   G__va_arg_put(&G__va_arg_bufobj, libp, 2);
      ((TMemStatDrawDlg*) G__getstructoffset())->EmitVA((const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]), G__va_arg_bufobj);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_282_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMemStatDrawDlg*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_282_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMemStatDrawDlg*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_282_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMemStatDrawDlg*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long_t*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_282_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMemStatDrawDlg*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Double_t) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_282_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMemStatDrawDlg*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_282_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMemStatDrawDlg*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long64_t) G__Longlong(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_282_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMemStatDrawDlg*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (ULong64_t) G__ULonglong(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_282_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMemStatDrawDlg*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_282_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMemStatDrawDlg*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Char_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_282_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMemStatDrawDlg*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UChar_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_282_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMemStatDrawDlg*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Short_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_282_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMemStatDrawDlg*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UShort_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_282_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMemStatDrawDlg*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_282_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMemStatDrawDlg*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_282_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMemStatDrawDlg*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (ULong_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_282_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMemStatDrawDlg*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Float_t) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_282_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMemStatDrawDlg*) G__getstructoffset())->Destroyed();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_282_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMemStatDrawDlg*) G__getstructoffset())->ChangedBy((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_282_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMemStatDrawDlg*) G__getstructoffset())->Message((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_282_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TMemStatDrawDlg* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 2
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new TMemStatDrawDlg((TGCompositeFrame*) G__int(libp->para[0]), (TMemStat*) G__int(libp->para[1]));
   } else {
     p = new((void*) gvp) TMemStatDrawDlg((TGCompositeFrame*) G__int(libp->para[0]), (TMemStat*) G__int(libp->para[1]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__G__MemstatGuiLN_TMemStatDrawDlg));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__MemstatGui_282_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMemStatDrawDlg*) G__getstructoffset())->HandleDrawMemStat();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TMemStatDrawDlg G__TTMemStatDrawDlg;
static int G__G__MemstatGui_282_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TMemStatDrawDlg*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TMemStatDrawDlg*) (soff+(sizeof(TMemStatDrawDlg)*i)))->~G__TTMemStatDrawDlg();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TMemStatDrawDlg*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TMemStatDrawDlg*) (soff))->~G__TTMemStatDrawDlg();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TMemStatViewerGUI */

/* TMemStatDrawDlg */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncG__MemstatGui {
 public:
  G__Sizep2memfuncG__MemstatGui(): p(&G__Sizep2memfuncG__MemstatGui::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncG__MemstatGui::*p)();
};

size_t G__get_sizep2memfuncG__MemstatGui()
{
  G__Sizep2memfuncG__MemstatGui a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceG__MemstatGui() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__G__MemstatGuiLN_TMemStatViewerGUI))) {
     TMemStatViewerGUI *G__Lderived;
     G__Lderived=(TMemStatViewerGUI*)0x1000;
     {
       TGCompositeFrame *G__Lpbase=(TGCompositeFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__MemstatGuiLN_TMemStatViewerGUI),G__get_linked_tagnum(&G__G__MemstatGuiLN_TGCompositeFrame),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGFrame *G__Lpbase=(TGFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__MemstatGuiLN_TMemStatViewerGUI),G__get_linked_tagnum(&G__G__MemstatGuiLN_TGFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGWindow *G__Lpbase=(TGWindow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__MemstatGuiLN_TMemStatViewerGUI),G__get_linked_tagnum(&G__G__MemstatGuiLN_TGWindow),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGObject *G__Lpbase=(TGObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__MemstatGuiLN_TMemStatViewerGUI),G__get_linked_tagnum(&G__G__MemstatGuiLN_TGObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__MemstatGuiLN_TMemStatViewerGUI),G__get_linked_tagnum(&G__G__MemstatGuiLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__MemstatGuiLN_TMemStatViewerGUI),G__get_linked_tagnum(&G__G__MemstatGuiLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableG__MemstatGui() {

   /* Setting up typedef entry */
   G__search_typename2("Char_t",99,-1,0,-1);
   G__setnewtype(-1,"Signed Character 1 byte (char)",0);
   G__search_typename2("UChar_t",98,-1,0,-1);
   G__setnewtype(-1,"Unsigned Character 1 byte (unsigned char)",0);
   G__search_typename2("Short_t",115,-1,0,-1);
   G__setnewtype(-1,"Signed Short integer 2 bytes (short)",0);
   G__search_typename2("UShort_t",114,-1,0,-1);
   G__setnewtype(-1,"Unsigned Short integer 2 bytes (unsigned short)",0);
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Long_t",108,-1,0,-1);
   G__setnewtype(-1,"Signed long integer 4 bytes (long)",0);
   G__search_typename2("ULong_t",107,-1,0,-1);
   G__setnewtype(-1,"Unsigned long integer 4 bytes (unsigned long)",0);
   G__search_typename2("Float_t",102,-1,0,-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("Option_t",99,-1,256,-1);
   G__setnewtype(-1,"Option string (const char)",0);
   G__search_typename2("Long64_t",110,-1,0,-1);
   G__setnewtype(-1,"Portable signed long integer 8 bytes",0);
   G__search_typename2("ULong64_t",109,-1,0,-1);
   G__setnewtype(-1,"Portable unsigned long integer 8 bytes",0);
   G__search_typename2("vector<TSchemaHelper>",117,G__get_linked_tagnum(&G__G__MemstatGuiLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G__MemstatGuiLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__MemstatGuiLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G__MemstatGuiLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__MemstatGuiLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__G__MemstatGuiLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__G__MemstatGuiLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__G__MemstatGuiLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__G__MemstatGuiLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__G__MemstatGuiLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__G__MemstatGuiLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G__MemstatGuiLN_reverse_iteratorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__MemstatGuiLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G__MemstatGuiLN_reverse_iteratorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__MemstatGuiLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<unsigned int>",117,G__get_linked_tagnum(&G__G__MemstatGuiLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Int_t>",117,G__get_linked_tagnum(&G__G__MemstatGuiLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G__MemstatGuiLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__MemstatGuiLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G__MemstatGuiLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__MemstatGuiLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__G__MemstatGuiLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<std::string>",117,G__get_linked_tagnum(&G__G__MemstatGuiLN_setlEstringcOlesslEstringgRcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<string>",117,G__get_linked_tagnum(&G__G__MemstatGuiLN_setlEstringcOlesslEstringgRcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("set<string,less<string> >",117,G__get_linked_tagnum(&G__G__MemstatGuiLN_setlEstringcOlesslEstringgRcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::string>",117,G__get_linked_tagnum(&G__G__MemstatGuiLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G__MemstatGuiLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__MemstatGuiLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G__MemstatGuiLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__MemstatGuiLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__G__MemstatGuiLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("StringVector_t",117,G__get_linked_tagnum(&G__G__MemstatGuiLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TMemStatViewerGUI */
static void G__setup_memvarTMemStatViewerGUI(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__G__MemstatGuiLN_TMemStatViewerGUI));
   { TMemStatViewerGUI *p; p=(TMemStatViewerGUI*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__MemstatGuiLN_TMemStat),-1,-1,2,"fViewer=",0,"CalibViewer object used for drawing");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__MemstatGuiLN_TGTextView),-1,-1,2,"fText=",0,"text widget");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__MemstatGuiLN_TGNumberEntry),-1,-1,2,"fNmbStackDeep=",0,"number entry box for specifying the stack deepness");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__MemstatGuiLN_TGNumberEntry),-1,-1,2,"fNmbSortDeep=",0,"number entry box for specifying the number of stamps");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__G__MemstatGuiLN_string),-1,-1,2,"fCurLib=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__G__MemstatGuiLN_string),-1,-1,2,"fCurFunc=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__MemstatGuiLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* TMemStatDrawDlg */
static void G__setup_memvarTMemStatDrawDlg(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__G__MemstatGuiLN_TMemStatDrawDlg));
   { TMemStatDrawDlg *p; p=(TMemStatDrawDlg*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__G__MemstatGuiLN_TQObjSender),-1,-1,4,"fQObject=",0,(char*)NULL);
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__MemstatGuiLN_TMemStat),-1,-1,4,"fMemStat=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__MemstatGuiLN_TGComboBox),-1,-1,4,"fboxOrder=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__MemstatGuiLN_TGComboBox),-1,-1,4,"fboxSortStat=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__MemstatGuiLN_TGComboBox),-1,-1,4,"fboxSortStamp=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__MemstatGuiLN_TGNumberEntry),-1,-1,4,"fNmbStackDeep=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__MemstatGuiLN_TGNumberEntry),-1,-1,4,"fNmbSortDeep=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__MemstatGuiLN_TGNumberEntry),-1,-1,4,"fNmbMaxLength=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__MemstatGuiLN_TRootEmbeddedCanvas),-1,-1,4,"fEc=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarG__MemstatGui() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTMemStatViewerGUI(void) {
   /* TMemStatViewerGUI */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__G__MemstatGuiLN_TMemStatViewerGUI));
   G__memfunc_setup("MakeContSortStat",1622,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 2, 0, "U 'TGCompositeFrame' - 0 - frame", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MakeContSortStamp",1727,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 2, 0, "U 'TGCompositeFrame' - 0 - frame", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MakeContDeep",1168,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 2, 0, "U 'TGCompositeFrame' - 0 - frame", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MakeStampList",1311,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 2, 0, "U 'TGCompositeFrame' - 0 - frame", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MakeSelection",1316,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 2, 0, "U 'TGCompositeFrame' - 0 - frame", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Initialize",1042,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 2, 0, "C - 'Option_t' 10 - option", "initializes the GUI with default settings and opens tree for drawing", (void*) NULL, 0);
   G__memfunc_setup("MakePrint",907,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 2, 0, "", "get print", (void*) NULL, 0);
   G__memfunc_setup("TMemStatViewerGUI",1638,G__G__MemstatGui_277_0_8, 105, G__get_linked_tagnum(&G__G__MemstatGuiLN_TMemStatViewerGUI), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TMemStatViewerGUI",1638,G__G__MemstatGui_277_0_9, 105, G__get_linked_tagnum(&G__G__MemstatGuiLN_TMemStatViewerGUI), -1, 0, 4, 1, 1, 0, 
"U 'TGWindow' - 10 - p h - 'UInt_t' 0 - w "
"h - 'UInt_t' 0 - h C - 'Option_t' 10 '\"read\"' option", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ShowGUI",646,G__G__MemstatGui_277_0_10, 121, -1, -1, 0, 0, 3, 1, 0, "", "initialize and show GUI for presentation", (void*) G__func2void( (void (*)())(&TMemStatViewerGUI::ShowGUI) ), 0);
   G__memfunc_setup("HandleButtonsSortStat",2175,G__G__MemstatGui_277_0_11, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 '-1' id", "handles mutual radio button for sort stat", (void*) NULL, 0);
   G__memfunc_setup("HandleButtonsSortStamp",2280,G__G__MemstatGui_277_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 '-1' id", "handles mutual radio button for sort stamp", (void*) NULL, 0);
   G__memfunc_setup("HandleDeep",970,G__G__MemstatGui_277_0_13, 121, -1, -1, 0, 1, 1, 1, 0, "l - 'Long_t' 0 - id", "handles stack deep and nrows", (void*) NULL, 0);
   G__memfunc_setup("HandleStampSelect",1713,G__G__MemstatGui_277_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("HandleFuncSelect",1592,G__G__MemstatGui_277_0_15, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("HandleLibSelect",1475,G__G__MemstatGui_277_0_16, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__G__MemstatGui_277_0_17, 85, G__get_linked_tagnum(&G__G__MemstatGuiLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TMemStatViewerGUI::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__G__MemstatGui_277_0_18, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TMemStatViewerGUI::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__G__MemstatGui_277_0_19, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TMemStatViewerGUI::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__G__MemstatGui_277_0_20, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TMemStatViewerGUI::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__G__MemstatGuiLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__G__MemstatGui_277_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__G__MemstatGui_277_0_25, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TMemStatViewerGUI::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__G__MemstatGui_277_0_26, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TMemStatViewerGUI::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__G__MemstatGui_277_0_27, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TMemStatViewerGUI::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__G__MemstatGui_277_0_28, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TMemStatViewerGUI::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~TMemStatViewerGUI", 1764, G__G__MemstatGui_277_0_29, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncTMemStatDrawDlg(void) {
   /* TMemStatDrawDlg */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__G__MemstatGuiLN_TMemStatDrawDlg));
   G__memfunc_setup("GetListOfSignals",1602,G__G__MemstatGui_282_0_1, 85, G__get_linked_tagnum(&G__G__MemstatGuiLN_TList), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Connect",714,G__G__MemstatGui_282_0_2, 103, -1, G__defined_typename("Bool_t"), 0, 4, 1, 1, 0, 
"C - - 10 - sig C - - 10 - cl "
"Y - - 0 - rcvr C - - 10 - slt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Disconnect",1034,G__G__MemstatGui_282_0_3, 103, -1, G__defined_typename("Bool_t"), 0, 3, 1, 1, 0, 
"C - - 10 '0' sig Y - - 0 '0' rcvr "
"C - - 10 '0' slt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("HighPriority",1250,G__G__MemstatGui_282_0_4, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal_name C - - 10 '0' slot_name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("LowPriority",1172,G__G__MemstatGui_282_0_5, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal_name C - - 10 '0' slot_name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EmitVA",550,G__G__MemstatGui_282_0_6, 121, -1, -1, 0, 2, 8, 1, 0, 
"C - - 10 - signal i - 'Int_t' 0 - nargs", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__G__MemstatGui_282_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - signal", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__G__MemstatGui_282_0_8, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal C - - 10 - params", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__G__MemstatGui_282_0_9, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal L - 'Long_t' 0 - paramArr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__G__MemstatGui_282_0_10, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal d - 'Double_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__G__MemstatGui_282_0_11, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal l - 'Long_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__G__MemstatGui_282_0_12, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal n - 'Long64_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__G__MemstatGui_282_0_13, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal m - 'ULong64_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__G__MemstatGui_282_0_14, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal g - 'Bool_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__G__MemstatGui_282_0_15, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal c - 'Char_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__G__MemstatGui_282_0_16, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal b - 'UChar_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__G__MemstatGui_282_0_17, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal s - 'Short_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__G__MemstatGui_282_0_18, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal r - 'UShort_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__G__MemstatGui_282_0_19, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal i - 'Int_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__G__MemstatGui_282_0_20, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal h - 'UInt_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__G__MemstatGui_282_0_21, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal k - 'ULong_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__G__MemstatGui_282_0_22, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal f - 'Float_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Destroyed",947,G__G__MemstatGui_282_0_23, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ChangedBy",869,G__G__MemstatGui_282_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - method", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Message",709,G__G__MemstatGui_282_0_25, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - msg", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TMemStatDrawDlg",1460,G__G__MemstatGui_282_0_26, 105, G__get_linked_tagnum(&G__G__MemstatGuiLN_TMemStatDrawDlg), -1, 0, 2, 1, 1, 0, 
"U 'TGCompositeFrame' - 0 - parent U 'TMemStat' - 0 - MemStat", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("HandleDrawMemStat",1685,G__G__MemstatGui_282_0_27, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlaceCtrls",1005,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 0, "U 'TGCompositeFrame' - 0 - frame", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlaceLBoxCtrl",1263,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 5, 1, 4, 0, 
"U 'TGCompositeFrame' - 0 - frame U 'TGComboBox' - 2 - box "
"u 'string' - 11 - Label u 'vector<string,allocator<string> >' 'StringVector_t' 11 - Vealues "
"i - 'Int_t' 0 - resource", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlaceDeepCtrl",1272,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 0, "U 'TGCompositeFrame' - 0 - frame", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PlaceEmbeddedCanvas",1867,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 0, "U 'TGCompositeFrame' - 0 - frame", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReDraw",581,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TMemStatDrawDlg", 1586, G__G__MemstatGui_282_0_33, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncG__MemstatGui() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalG__MemstatGui() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcG__MemstatGui() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__G__MemstatGuiLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__G__MemstatGuiLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__G__MemstatGuiLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__G__MemstatGuiLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__G__MemstatGuiLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__G__MemstatGuiLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__G__MemstatGuiLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__G__MemstatGuiLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__G__MemstatGuiLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__G__MemstatGuiLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__G__MemstatGuiLN_reverse_iteratorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<unsigned int,allocator<unsigned int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__G__MemstatGuiLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__G__MemstatGuiLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__G__MemstatGuiLN_TMemStat = { "TMemStat" , 99 , -1 };
G__linked_taginfo G__G__MemstatGuiLN_setlEstringcOlesslEstringgRcOallocatorlEstringgRsPgR = { "set<string,less<string>,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__G__MemstatGuiLN_TGObject = { "TGObject" , 99 , -1 };
G__linked_taginfo G__G__MemstatGuiLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__G__MemstatGuiLN_TQObjSender = { "TQObjSender" , 99 , -1 };
G__linked_taginfo G__G__MemstatGuiLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__G__MemstatGuiLN_TGFrame = { "TGFrame" , 99 , -1 };
G__linked_taginfo G__G__MemstatGuiLN_TGCompositeFrame = { "TGCompositeFrame" , 99 , -1 };
G__linked_taginfo G__G__MemstatGuiLN_TGTextView = { "TGTextView" , 99 , -1 };
G__linked_taginfo G__G__MemstatGuiLN_TGNumberEntry = { "TGNumberEntry" , 99 , -1 };
G__linked_taginfo G__G__MemstatGuiLN_TGComboBox = { "TGComboBox" , 99 , -1 };
G__linked_taginfo G__G__MemstatGuiLN_TMemStatViewerGUI = { "TMemStatViewerGUI" , 99 , -1 };
G__linked_taginfo G__G__MemstatGuiLN_TRootEmbeddedCanvas = { "TRootEmbeddedCanvas" , 99 , -1 };
G__linked_taginfo G__G__MemstatGuiLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__G__MemstatGuiLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G__G__MemstatGuiLN_TMemStatDrawDlg = { "TMemStatDrawDlg" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableG__MemstatGui() {
  G__G__MemstatGuiLN_TClass.tagnum = -1 ;
  G__G__MemstatGuiLN_TBuffer.tagnum = -1 ;
  G__G__MemstatGuiLN_TMemberInspector.tagnum = -1 ;
  G__G__MemstatGuiLN_TObject.tagnum = -1 ;
  G__G__MemstatGuiLN_string.tagnum = -1 ;
  G__G__MemstatGuiLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__G__MemstatGuiLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__G__MemstatGuiLN_TList.tagnum = -1 ;
  G__G__MemstatGuiLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__G__MemstatGuiLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__G__MemstatGuiLN_reverse_iteratorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__G__MemstatGuiLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__G__MemstatGuiLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__G__MemstatGuiLN_TMemStat.tagnum = -1 ;
  G__G__MemstatGuiLN_setlEstringcOlesslEstringgRcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__G__MemstatGuiLN_TGObject.tagnum = -1 ;
  G__G__MemstatGuiLN_TQObject.tagnum = -1 ;
  G__G__MemstatGuiLN_TQObjSender.tagnum = -1 ;
  G__G__MemstatGuiLN_TGWindow.tagnum = -1 ;
  G__G__MemstatGuiLN_TGFrame.tagnum = -1 ;
  G__G__MemstatGuiLN_TGCompositeFrame.tagnum = -1 ;
  G__G__MemstatGuiLN_TGTextView.tagnum = -1 ;
  G__G__MemstatGuiLN_TGNumberEntry.tagnum = -1 ;
  G__G__MemstatGuiLN_TGComboBox.tagnum = -1 ;
  G__G__MemstatGuiLN_TMemStatViewerGUI.tagnum = -1 ;
  G__G__MemstatGuiLN_TRootEmbeddedCanvas.tagnum = -1 ;
  G__G__MemstatGuiLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__G__MemstatGuiLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__G__MemstatGuiLN_TMemStatDrawDlg.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableG__MemstatGui() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__G__MemstatGuiLN_TClass);
   G__get_linked_tagnum_fwd(&G__G__MemstatGuiLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__G__MemstatGuiLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__G__MemstatGuiLN_TObject);
   G__get_linked_tagnum_fwd(&G__G__MemstatGuiLN_string);
   G__get_linked_tagnum_fwd(&G__G__MemstatGuiLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__G__MemstatGuiLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__G__MemstatGuiLN_TList);
   G__get_linked_tagnum_fwd(&G__G__MemstatGuiLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__G__MemstatGuiLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__G__MemstatGuiLN_reverse_iteratorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__G__MemstatGuiLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__G__MemstatGuiLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__G__MemstatGuiLN_TMemStat);
   G__get_linked_tagnum_fwd(&G__G__MemstatGuiLN_setlEstringcOlesslEstringgRcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__G__MemstatGuiLN_TGObject);
   G__get_linked_tagnum_fwd(&G__G__MemstatGuiLN_TQObject);
   G__get_linked_tagnum_fwd(&G__G__MemstatGuiLN_TQObjSender);
   G__get_linked_tagnum_fwd(&G__G__MemstatGuiLN_TGWindow);
   G__get_linked_tagnum_fwd(&G__G__MemstatGuiLN_TGFrame);
   G__get_linked_tagnum_fwd(&G__G__MemstatGuiLN_TGCompositeFrame);
   G__get_linked_tagnum_fwd(&G__G__MemstatGuiLN_TGTextView);
   G__get_linked_tagnum_fwd(&G__G__MemstatGuiLN_TGNumberEntry);
   G__get_linked_tagnum_fwd(&G__G__MemstatGuiLN_TGComboBox);
   G__tagtable_setup(G__get_linked_tagnum(&G__G__MemstatGuiLN_TMemStatViewerGUI),sizeof(TMemStatViewerGUI),-1,324864,"a GUI class of memstat",G__setup_memvarTMemStatViewerGUI,G__setup_memfuncTMemStatViewerGUI);
   G__get_linked_tagnum_fwd(&G__G__MemstatGuiLN_TRootEmbeddedCanvas);
   G__get_linked_tagnum_fwd(&G__G__MemstatGuiLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__G__MemstatGuiLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum(&G__G__MemstatGuiLN_TMemStatDrawDlg),sizeof(TMemStatDrawDlg),-1,295936,(char*)NULL,G__setup_memvarTMemStatDrawDlg,G__setup_memfuncTMemStatDrawDlg);
}
extern "C" void G__cpp_setupG__MemstatGui(void) {
  G__check_setup_version(30051515,"G__cpp_setupG__MemstatGui()");
  G__set_cpp_environmentG__MemstatGui();
  G__cpp_setup_tagtableG__MemstatGui();

  G__cpp_setup_inheritanceG__MemstatGui();

  G__cpp_setup_typetableG__MemstatGui();

  G__cpp_setup_memvarG__MemstatGui();

  G__cpp_setup_memfuncG__MemstatGui();
  G__cpp_setup_globalG__MemstatGui();
  G__cpp_setup_funcG__MemstatGui();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncG__MemstatGui();
  return;
}
class G__cpp_setup_initG__MemstatGui {
  public:
    G__cpp_setup_initG__MemstatGui() { G__add_setup_func("G__MemstatGui",(G__incsetup)(&G__cpp_setupG__MemstatGui)); G__call_setup_funcs(); }
   ~G__cpp_setup_initG__MemstatGui() { G__remove_setup_func("G__MemstatGui"); }
};
G__cpp_setup_initG__MemstatGui G__cpp_setup_initializerG__MemstatGui;

