/********************************************************************
* misc/memstat/src/G__MemstatGui.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error misc/memstat/src/G__MemstatGui.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableG__MemstatGui();
extern void G__cpp_setup_inheritanceG__MemstatGui();
extern void G__cpp_setup_typetableG__MemstatGui();
extern void G__cpp_setup_memvarG__MemstatGui();
extern void G__cpp_setup_globalG__MemstatGui();
extern void G__cpp_setup_memfuncG__MemstatGui();
extern void G__cpp_setup_funcG__MemstatGui();
extern void G__set_cpp_environmentG__MemstatGui();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TMemStat.h"
#include "TMemStatViewerGUI.h"
#include "TMemStatDrawDlg.h"
#include "TMemStatResource.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__MemstatGuiLN_TClass;
extern G__linked_taginfo G__G__MemstatGuiLN_TBuffer;
extern G__linked_taginfo G__G__MemstatGuiLN_TMemberInspector;
extern G__linked_taginfo G__G__MemstatGuiLN_TObject;
extern G__linked_taginfo G__G__MemstatGuiLN_string;
extern G__linked_taginfo G__G__MemstatGuiLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__MemstatGuiLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__MemstatGuiLN_TList;
extern G__linked_taginfo G__G__MemstatGuiLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__G__MemstatGuiLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__G__MemstatGuiLN_reverse_iteratorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__MemstatGuiLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__G__MemstatGuiLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__MemstatGuiLN_TMemStat;
extern G__linked_taginfo G__G__MemstatGuiLN_setlEstringcOlesslEstringgRcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__G__MemstatGuiLN_TGObject;
extern G__linked_taginfo G__G__MemstatGuiLN_TQObject;
extern G__linked_taginfo G__G__MemstatGuiLN_TQObjSender;
extern G__linked_taginfo G__G__MemstatGuiLN_TGWindow;
extern G__linked_taginfo G__G__MemstatGuiLN_TGFrame;
extern G__linked_taginfo G__G__MemstatGuiLN_TGCompositeFrame;
extern G__linked_taginfo G__G__MemstatGuiLN_TGTextView;
extern G__linked_taginfo G__G__MemstatGuiLN_TGNumberEntry;
extern G__linked_taginfo G__G__MemstatGuiLN_TGComboBox;
extern G__linked_taginfo G__G__MemstatGuiLN_TMemStatViewerGUI;
extern G__linked_taginfo G__G__MemstatGuiLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__G__MemstatGuiLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__G__MemstatGuiLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__MemstatGuiLN_TMemStatDrawDlg;

/* STUB derived class for protected member access */
