//
// File generated by core/utils/src/rootcint_tmp at Mon Apr 13 13:49:29 2015

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "G__PgSQL.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void TPgSQLResult_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void delete_TPgSQLResult(void *p);
   static void deleteArray_TPgSQLResult(void *p);
   static void destruct_TPgSQLResult(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TPgSQLResult*)
   {
      ::TPgSQLResult *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TPgSQLResult >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TPgSQLResult", ::TPgSQLResult::Class_Version(), "include/TPgSQLResult.h", 26,
                  typeid(::TPgSQLResult), DefineBehavior(ptr, ptr),
                  &::TPgSQLResult::Dictionary, isa_proxy, 0,
                  sizeof(::TPgSQLResult) );
      instance.SetDelete(&delete_TPgSQLResult);
      instance.SetDeleteArray(&deleteArray_TPgSQLResult);
      instance.SetDestructor(&destruct_TPgSQLResult);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TPgSQLResult*)
   {
      return GenerateInitInstanceLocal((::TPgSQLResult*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TPgSQLResult*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

namespace ROOT {
   void TPgSQLRow_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void delete_TPgSQLRow(void *p);
   static void deleteArray_TPgSQLRow(void *p);
   static void destruct_TPgSQLRow(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TPgSQLRow*)
   {
      ::TPgSQLRow *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TPgSQLRow >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TPgSQLRow", ::TPgSQLRow::Class_Version(), "include/TPgSQLRow.h", 27,
                  typeid(::TPgSQLRow), DefineBehavior(ptr, ptr),
                  &::TPgSQLRow::Dictionary, isa_proxy, 0,
                  sizeof(::TPgSQLRow) );
      instance.SetDelete(&delete_TPgSQLRow);
      instance.SetDeleteArray(&deleteArray_TPgSQLRow);
      instance.SetDestructor(&destruct_TPgSQLRow);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TPgSQLRow*)
   {
      return GenerateInitInstanceLocal((::TPgSQLRow*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TPgSQLRow*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

namespace ROOT {
   void TPgSQLServer_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void delete_TPgSQLServer(void *p);
   static void deleteArray_TPgSQLServer(void *p);
   static void destruct_TPgSQLServer(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TPgSQLServer*)
   {
      ::TPgSQLServer *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TPgSQLServer >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TPgSQLServer", ::TPgSQLServer::Class_Version(), "include/TPgSQLServer.h", 27,
                  typeid(::TPgSQLServer), DefineBehavior(ptr, ptr),
                  &::TPgSQLServer::Dictionary, isa_proxy, 0,
                  sizeof(::TPgSQLServer) );
      instance.SetDelete(&delete_TPgSQLServer);
      instance.SetDeleteArray(&deleteArray_TPgSQLServer);
      instance.SetDestructor(&destruct_TPgSQLServer);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TPgSQLServer*)
   {
      return GenerateInitInstanceLocal((::TPgSQLServer*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TPgSQLServer*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

namespace ROOT {
   void TPgSQLStatement_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void delete_TPgSQLStatement(void *p);
   static void deleteArray_TPgSQLStatement(void *p);
   static void destruct_TPgSQLStatement(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TPgSQLStatement*)
   {
      ::TPgSQLStatement *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TPgSQLStatement >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TPgSQLStatement", ::TPgSQLStatement::Class_Version(), "include/TPgSQLStatement.h", 46,
                  typeid(::TPgSQLStatement), DefineBehavior(ptr, ptr),
                  &::TPgSQLStatement::Dictionary, isa_proxy, 0,
                  sizeof(::TPgSQLStatement) );
      instance.SetDelete(&delete_TPgSQLStatement);
      instance.SetDeleteArray(&deleteArray_TPgSQLStatement);
      instance.SetDestructor(&destruct_TPgSQLStatement);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TPgSQLStatement*)
   {
      return GenerateInitInstanceLocal((::TPgSQLStatement*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TPgSQLStatement*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *TPgSQLResult::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TPgSQLResult::Class_Name()
{
   return "TPgSQLResult";
}

//______________________________________________________________________________
const char *TPgSQLResult::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TPgSQLResult*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TPgSQLResult::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TPgSQLResult*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TPgSQLResult::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TPgSQLResult*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TPgSQLResult::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TPgSQLResult*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
TClass *TPgSQLRow::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TPgSQLRow::Class_Name()
{
   return "TPgSQLRow";
}

//______________________________________________________________________________
const char *TPgSQLRow::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TPgSQLRow*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TPgSQLRow::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TPgSQLRow*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TPgSQLRow::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TPgSQLRow*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TPgSQLRow::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TPgSQLRow*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
TClass *TPgSQLServer::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TPgSQLServer::Class_Name()
{
   return "TPgSQLServer";
}

//______________________________________________________________________________
const char *TPgSQLServer::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TPgSQLServer*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TPgSQLServer::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TPgSQLServer*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TPgSQLServer::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TPgSQLServer*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TPgSQLServer::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TPgSQLServer*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
TClass *TPgSQLStatement::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TPgSQLStatement::Class_Name()
{
   return "TPgSQLStatement";
}

//______________________________________________________________________________
const char *TPgSQLStatement::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TPgSQLStatement*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TPgSQLStatement::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TPgSQLStatement*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TPgSQLStatement::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TPgSQLStatement*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TPgSQLStatement::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TPgSQLStatement*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void TPgSQLServer::Streamer(TBuffer &R__b)
{
   // Stream an object of class TPgSQLServer.

   TSQLServer::Streamer(R__b);
}

//______________________________________________________________________________
void TPgSQLServer::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class TPgSQLServer.
      TClass *R__cl = ::TPgSQLServer::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "*fPgSQL", &fPgSQL);
      TSQLServer::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_TPgSQLServer(void *p) {
      delete ((::TPgSQLServer*)p);
   }
   static void deleteArray_TPgSQLServer(void *p) {
      delete [] ((::TPgSQLServer*)p);
   }
   static void destruct_TPgSQLServer(void *p) {
      typedef ::TPgSQLServer current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::TPgSQLServer

//______________________________________________________________________________
void TPgSQLResult::Streamer(TBuffer &R__b)
{
   // Stream an object of class TPgSQLResult.

   TSQLResult::Streamer(R__b);
}

//______________________________________________________________________________
void TPgSQLResult::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class TPgSQLResult.
      TClass *R__cl = ::TPgSQLResult::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "*fResult", &fResult);
      R__insp.Inspect(R__cl, R__parent, "fCurrentRow", &fCurrentRow);
      TSQLResult::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_TPgSQLResult(void *p) {
      delete ((::TPgSQLResult*)p);
   }
   static void deleteArray_TPgSQLResult(void *p) {
      delete [] ((::TPgSQLResult*)p);
   }
   static void destruct_TPgSQLResult(void *p) {
      typedef ::TPgSQLResult current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::TPgSQLResult

//______________________________________________________________________________
void TPgSQLRow::Streamer(TBuffer &R__b)
{
   // Stream an object of class TPgSQLRow.

   TSQLRow::Streamer(R__b);
}

//______________________________________________________________________________
void TPgSQLRow::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class TPgSQLRow.
      TClass *R__cl = ::TPgSQLRow::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "*fResult", &fResult);
      R__insp.Inspect(R__cl, R__parent, "fRowNum", &fRowNum);
      TSQLRow::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_TPgSQLRow(void *p) {
      delete ((::TPgSQLRow*)p);
   }
   static void deleteArray_TPgSQLRow(void *p) {
      delete [] ((::TPgSQLRow*)p);
   }
   static void destruct_TPgSQLRow(void *p) {
      typedef ::TPgSQLRow current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::TPgSQLRow

//______________________________________________________________________________
void TPgSQLStatement::Streamer(TBuffer &R__b)
{
   // Stream an object of class TPgSQLStatement.

   TSQLStatement::Streamer(R__b);
}

//______________________________________________________________________________
void TPgSQLStatement::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class TPgSQLStatement.
      TClass *R__cl = ::TPgSQLStatement::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "*fStmt", &fStmt);
      R__insp.Inspect(R__cl, R__parent, "fNumBuffers", &fNumBuffers);
      R__insp.Inspect(R__cl, R__parent, "*fBind", &fBind);
      R__insp.Inspect(R__cl, R__parent, "*fFieldName", &fFieldName);
      R__insp.Inspect(R__cl, R__parent, "fWorkingMode", &fWorkingMode);
      R__insp.Inspect(R__cl, R__parent, "fIterationCount", &fIterationCount);
      R__insp.Inspect(R__cl, R__parent, "*fParamLengths", &fParamLengths);
      R__insp.Inspect(R__cl, R__parent, "*fParamFormats", &fParamFormats);
      R__insp.Inspect(R__cl, R__parent, "fNumResultRows", &fNumResultRows);
      R__insp.Inspect(R__cl, R__parent, "fNumResultCols", &fNumResultCols);
      TSQLStatement::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_TPgSQLStatement(void *p) {
      delete ((::TPgSQLStatement*)p);
   }
   static void deleteArray_TPgSQLStatement(void *p) {
      delete [] ((::TPgSQLStatement*)p);
   }
   static void destruct_TPgSQLStatement(void *p) {
      typedef ::TPgSQLStatement current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::TPgSQLStatement

/********************************************************
* sql/pgsql/src/G__PgSQL.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableG__PgSQL();

extern "C" void G__set_cpp_environmentG__PgSQL() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("TPgSQLResult.h");
  G__add_compiledheader("TPgSQLRow.h");
  G__add_compiledheader("TPgSQLServer.h");
  G__add_compiledheader("TPgSQLStatement.h");
  G__cpp_reset_tagtableG__PgSQL();
}
#include <new>
extern "C" int G__cpp_dllrevG__PgSQL() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TPgSQLResult */
static int G__G__PgSQL_98_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TPgSQLResult* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new TPgSQLResult((void*) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) TPgSQLResult((void*) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLResult));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__PgSQL_98_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TPgSQLResult::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__PgSQL_98_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TPgSQLResult::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__PgSQL_98_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TPgSQLResult::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__PgSQL_98_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TPgSQLResult::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__PgSQL_98_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TPgSQLResult*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__PgSQL_98_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TPgSQLResult::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__PgSQL_98_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TPgSQLResult::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__PgSQL_98_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TPgSQLResult::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__PgSQL_98_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TPgSQLResult::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__G__PgSQL_98_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TPgSQLResult* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TPgSQLResult(*(TPgSQLResult*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLResult));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TPgSQLResult G__TTPgSQLResult;
static int G__G__PgSQL_98_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TPgSQLResult*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TPgSQLResult*) (soff+(sizeof(TPgSQLResult)*i)))->~G__TTPgSQLResult();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TPgSQLResult*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TPgSQLResult*) (soff))->~G__TTPgSQLResult();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__G__PgSQL_98_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TPgSQLResult* dest = (TPgSQLResult*) G__getstructoffset();
   *dest = *(TPgSQLResult*) libp->para[0].ref;
   const TPgSQLResult& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* TPgSQLRow */
static int G__G__PgSQL_99_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TPgSQLRow* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 2
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new TPgSQLRow((void*) G__int(libp->para[0]), (ULong_t) G__int(libp->para[1]));
   } else {
     p = new((void*) gvp) TPgSQLRow((void*) G__int(libp->para[0]), (ULong_t) G__int(libp->para[1]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLRow));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__PgSQL_99_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TPgSQLRow::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__PgSQL_99_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TPgSQLRow::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__PgSQL_99_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TPgSQLRow::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__PgSQL_99_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TPgSQLRow::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__PgSQL_99_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TPgSQLRow*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__PgSQL_99_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TPgSQLRow::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__PgSQL_99_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TPgSQLRow::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__PgSQL_99_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TPgSQLRow::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__PgSQL_99_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TPgSQLRow::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__G__PgSQL_99_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TPgSQLRow* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TPgSQLRow(*(TPgSQLRow*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLRow));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TPgSQLRow G__TTPgSQLRow;
static int G__G__PgSQL_99_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TPgSQLRow*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TPgSQLRow*) (soff+(sizeof(TPgSQLRow)*i)))->~G__TTPgSQLRow();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TPgSQLRow*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TPgSQLRow*) (soff))->~G__TTPgSQLRow();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__G__PgSQL_99_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TPgSQLRow* dest = (TPgSQLRow*) G__getstructoffset();
   *dest = *(TPgSQLRow*) libp->para[0].ref;
   const TPgSQLRow& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* TPgSQLServer */
static int G__G__PgSQL_116_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TPgSQLServer* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 3
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new TPgSQLServer(
(const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (const char*) G__int(libp->para[2]));
   } else {
     p = new((void*) gvp) TPgSQLServer(
(const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (const char*) G__int(libp->para[2]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLServer));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__PgSQL_116_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TPgSQLServer::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__PgSQL_116_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TPgSQLServer::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__PgSQL_116_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TPgSQLServer::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__PgSQL_116_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TPgSQLServer::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__PgSQL_116_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TPgSQLServer*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__PgSQL_116_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TPgSQLServer::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__PgSQL_116_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TPgSQLServer::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__PgSQL_116_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TPgSQLServer::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__PgSQL_116_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TPgSQLServer::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__G__PgSQL_116_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TPgSQLServer* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TPgSQLServer(*(TPgSQLServer*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLServer));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TPgSQLServer G__TTPgSQLServer;
static int G__G__PgSQL_116_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TPgSQLServer*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TPgSQLServer*) (soff+(sizeof(TPgSQLServer)*i)))->~G__TTPgSQLServer();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TPgSQLServer*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TPgSQLServer*) (soff))->~G__TTPgSQLServer();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__G__PgSQL_116_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TPgSQLServer* dest = (TPgSQLServer*) G__getstructoffset();
   *dest = *(TPgSQLServer*) libp->para[0].ref;
   const TPgSQLServer& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* TPgSQLStatement */
static int G__G__PgSQL_119_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TPgSQLStatement* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 2:
     //m: 2
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TPgSQLStatement((PgSQL_Stmt_t*) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1]));
     } else {
       p = new((void*) gvp) TPgSQLStatement((PgSQL_Stmt_t*) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1]));
     }
     break;
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TPgSQLStatement((PgSQL_Stmt_t*) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) TPgSQLStatement((PgSQL_Stmt_t*) G__int(libp->para[0]));
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLStatement));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__PgSQL_119_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((TPgSQLStatement*) G__getstructoffset())->Close((Option_t*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((TPgSQLStatement*) G__getstructoffset())->Close();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__PgSQL_119_0_45(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TPgSQLStatement::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__PgSQL_119_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TPgSQLStatement::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__PgSQL_119_0_47(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TPgSQLStatement::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__PgSQL_119_0_48(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TPgSQLStatement::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__PgSQL_119_0_52(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TPgSQLStatement*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__PgSQL_119_0_53(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TPgSQLStatement::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__PgSQL_119_0_54(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TPgSQLStatement::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__PgSQL_119_0_55(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TPgSQLStatement::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__G__PgSQL_119_0_56(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TPgSQLStatement::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__G__PgSQL_119_0_57(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TPgSQLStatement* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TPgSQLStatement(*(TPgSQLStatement*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLStatement));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TPgSQLStatement G__TTPgSQLStatement;
static int G__G__PgSQL_119_0_58(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TPgSQLStatement*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TPgSQLStatement*) (soff+(sizeof(TPgSQLStatement)*i)))->~G__TTPgSQLStatement();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TPgSQLStatement*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TPgSQLStatement*) (soff))->~G__TTPgSQLStatement();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__G__PgSQL_119_0_59(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TPgSQLStatement* dest = (TPgSQLStatement*) G__getstructoffset();
   *dest = *(TPgSQLStatement*) libp->para[0].ref;
   const TPgSQLStatement& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TPgSQLResult */

/* TPgSQLRow */

/* TPgSQLServer */

/* TPgSQLStatement */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncG__PgSQL {
 public:
  G__Sizep2memfuncG__PgSQL(): p(&G__Sizep2memfuncG__PgSQL::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncG__PgSQL::*p)();
};

size_t G__get_sizep2memfuncG__PgSQL()
{
  G__Sizep2memfuncG__PgSQL a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceG__PgSQL() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLResult))) {
     TPgSQLResult *G__Lderived;
     G__Lderived=(TPgSQLResult*)0x1000;
     {
       TSQLResult *G__Lpbase=(TSQLResult*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLResult),G__get_linked_tagnum(&G__G__PgSQLLN_TSQLResult),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLResult),G__get_linked_tagnum(&G__G__PgSQLLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLRow))) {
     TPgSQLRow *G__Lderived;
     G__Lderived=(TPgSQLRow*)0x1000;
     {
       TSQLRow *G__Lpbase=(TSQLRow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLRow),G__get_linked_tagnum(&G__G__PgSQLLN_TSQLRow),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLRow),G__get_linked_tagnum(&G__G__PgSQLLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLServer))) {
     TPgSQLServer *G__Lderived;
     G__Lderived=(TPgSQLServer*)0x1000;
     {
       TSQLServer *G__Lpbase=(TSQLServer*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLServer),G__get_linked_tagnum(&G__G__PgSQLLN_TSQLServer),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLServer),G__get_linked_tagnum(&G__G__PgSQLLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLStatement))) {
     TPgSQLStatement *G__Lderived;
     G__Lderived=(TPgSQLStatement*)0x1000;
     {
       TSQLStatement *G__Lpbase=(TSQLStatement*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLStatement),G__get_linked_tagnum(&G__G__PgSQLLN_TSQLStatement),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLStatement),G__get_linked_tagnum(&G__G__PgSQLLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableG__PgSQL() {

   /* Setting up typedef entry */
   G__search_typename2("ULong_t",107,-1,0,-1);
   G__setnewtype(-1,"Unsigned long integer 4 bytes (unsigned long)",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("Option_t",99,-1,256,-1);
   G__setnewtype(-1,"Option string (const char)",0);
   G__search_typename2("vector<TSchemaHelper>",117,G__get_linked_tagnum(&G__G__PgSQLLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__G__PgSQLLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__PgSQLLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__G__PgSQLLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__G__PgSQLLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__G__PgSQLLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TPgSQLResult */
static void G__setup_memvarTPgSQLResult(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLResult));
   { TPgSQLResult *p; p=(TPgSQLResult*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__PgSQLLN_PGresult),-1,-1,4,"fResult=",0,"query result (rows)");
   G__memvar_setup((void*)0,107,0,0,-1,G__defined_typename("ULong_t"),-1,4,"fCurrentRow=",0,"info to result row");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__PgSQLLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* TPgSQLRow */
static void G__setup_memvarTPgSQLRow(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLRow));
   { TPgSQLRow *p; p=(TPgSQLRow*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__PgSQLLN_PGresult),-1,-1,4,"fResult=",0,"current result set");
   G__memvar_setup((void*)0,107,0,0,-1,G__defined_typename("ULong_t"),-1,4,"fRowNum=",0,"row number");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__PgSQLLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* TPgSQLServer */
static void G__setup_memvarTPgSQLServer(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLServer));
   { TPgSQLServer *p; p=(TPgSQLServer*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__PgSQLLN_PGconn),-1,-1,4,"fPgSQL=",0,"connection to PgSQL server");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__PgSQLLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* TPgSQLStatement */
static void G__setup_memvarTPgSQLStatement(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLStatement));
   { TPgSQLStatement *p; p=(TPgSQLStatement*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__PgSQLLN_PgSQL_Stmt_t),-1,-1,4,"fStmt=",0,"! executed statement");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fNumBuffers=",0,"! number of statement parameters");
   G__memvar_setup((void*)0,67,2,0,-1,-1,-1,4,"fBind=",0,"! array of data for input");
   G__memvar_setup((void*)0,67,2,0,-1,-1,-1,4,"fFieldName=",0,"! array of column names");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fWorkingMode=",0,"! 1 - setting parameters, 2 - retrieving results");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fIterationCount=",0,"! number of iteration");
   G__memvar_setup((void*)0,73,0,0,-1,-1,-1,4,"fParamLengths=",0,"! length of column");
   G__memvar_setup((void*)0,73,0,0,-1,-1,-1,4,"fParamFormats=",0,"! data type (OID)");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fNumResultRows=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,4,"fNumResultCols=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__G__PgSQLLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarG__PgSQL() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTPgSQLResult(void) {
   /* TPgSQLResult */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLResult));
   G__memfunc_setup("IsValid",684,(G__InterfaceMethod) NULL, 103, -1, G__defined_typename("Bool_t"), 0, 1, 1, 4, 0, "i - 'Int_t' 0 - field", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TPgSQLResult",1146,G__G__PgSQL_98_0_2, 105, G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLResult), -1, 0, 1, 1, 1, 0, "Y - - 0 - result", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Close",502,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - 'Option_t' 10 '\"\"' opt", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetFieldCount",1293,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetFieldName",1157,(G__InterfaceMethod) NULL,67, -1, -1, 0, 1, 1, 1, 1, "i - 'Int_t' 0 - field", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Next",415,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__G__PgSQLLN_TSQLRow), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__G__PgSQL_98_0_7, 85, G__get_linked_tagnum(&G__G__PgSQLLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TPgSQLResult::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__G__PgSQL_98_0_8, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TPgSQLResult::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__G__PgSQL_98_0_9, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TPgSQLResult::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__G__PgSQL_98_0_10, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TPgSQLResult::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__G__PgSQLLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__G__PgSQL_98_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__G__PgSQL_98_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TPgSQLResult::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__G__PgSQL_98_0_16, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TPgSQLResult::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__G__PgSQL_98_0_17, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TPgSQLResult::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__G__PgSQL_98_0_18, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TPgSQLResult::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("TPgSQLResult", 1146, G__G__PgSQL_98_0_19, (int) ('i'), G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLResult), -1, 0, 1, 1, 1, 0, "u 'TPgSQLResult' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TPgSQLResult", 1272, G__G__PgSQL_98_0_20, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__G__PgSQL_98_0_21, (int) ('u'), G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLResult), -1, 1, 1, 1, 1, 0, "u 'TPgSQLResult' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncTPgSQLRow(void) {
   /* TPgSQLRow */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLRow));
   G__memfunc_setup("IsValid",684,(G__InterfaceMethod) NULL, 103, -1, G__defined_typename("Bool_t"), 0, 1, 1, 4, 0, "i - 'Int_t' 0 - field", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TPgSQLRow",819,G__G__PgSQL_99_0_2, 105, G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLRow), -1, 0, 2, 1, 1, 0, 
"Y - - 0 - result k - 'ULong_t' 0 - rowHandle", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Close",502,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - 'Option_t' 10 '\"\"' opt", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetFieldLength",1382,(G__InterfaceMethod) NULL,107, -1, G__defined_typename("ULong_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - field", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetField",772,(G__InterfaceMethod) NULL,67, -1, -1, 0, 1, 1, 1, 1, "i - 'Int_t' 0 - field", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__G__PgSQL_99_0_6, 85, G__get_linked_tagnum(&G__G__PgSQLLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TPgSQLRow::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__G__PgSQL_99_0_7, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TPgSQLRow::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__G__PgSQL_99_0_8, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TPgSQLRow::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__G__PgSQL_99_0_9, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TPgSQLRow::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__G__PgSQLLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__G__PgSQL_99_0_13, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__G__PgSQL_99_0_14, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TPgSQLRow::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__G__PgSQL_99_0_15, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TPgSQLRow::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__G__PgSQL_99_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TPgSQLRow::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__G__PgSQL_99_0_17, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TPgSQLRow::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("TPgSQLRow", 819, G__G__PgSQL_99_0_18, (int) ('i'), G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLRow), -1, 0, 1, 1, 1, 0, "u 'TPgSQLRow' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TPgSQLRow", 945, G__G__PgSQL_99_0_19, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__G__PgSQL_99_0_20, (int) ('u'), G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLRow), -1, 1, 1, 1, 1, 0, "u 'TPgSQLRow' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncTPgSQLServer(void) {
   /* TPgSQLServer */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLServer));
   G__memfunc_setup("TPgSQLServer",1138,G__G__PgSQL_116_0_1, 105, G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLServer), -1, 0, 3, 1, 1, 0, 
"C - - 10 - db C - - 10 - uid "
"C - - 10 - pw", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Close",502,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "C - 'Option_t' 10 '\"\"' opt", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Query",534,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__G__PgSQLLN_TSQLResult), -1, 0, 1, 1, 1, 0, "C - - 10 - sql", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Statement",949,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__G__PgSQLLN_TSQLStatement), -1, 0, 2, 1, 1, 0, 
"C - - 10 - sql i - 'Int_t' 0 '100' -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("HasStatement",1233,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SelectDataBase",1365,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "C - - 10 - dbname", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetDataBases",1160,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__G__PgSQLLN_TSQLResult), -1, 0, 1, 1, 1, 0, "C - - 10 '0' wild", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetTables",891,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__G__PgSQLLN_TSQLResult), -1, 0, 2, 1, 1, 0, 
"C - - 10 - dbname C - - 10 '0' wild", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetColumns",1025,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__G__PgSQLLN_TSQLResult), -1, 0, 3, 1, 1, 0, 
"C - - 10 - dbname C - - 10 - table "
"C - - 10 '0' wild", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("CreateDataBase",1353,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "C - - 10 - dbname", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("DropDataBase",1162,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "C - - 10 - dbname", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Reload",599,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Shutdown",860,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ServerInfo",1027,(G__InterfaceMethod) NULL,67, -1, -1, 0, 0, 1, 1, 1, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__G__PgSQL_116_0_15, 85, G__get_linked_tagnum(&G__G__PgSQLLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TPgSQLServer::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__G__PgSQL_116_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TPgSQLServer::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__G__PgSQL_116_0_17, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TPgSQLServer::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__G__PgSQL_116_0_18, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TPgSQLServer::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__G__PgSQLLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__G__PgSQL_116_0_22, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__G__PgSQL_116_0_23, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TPgSQLServer::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__G__PgSQL_116_0_24, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TPgSQLServer::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__G__PgSQL_116_0_25, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TPgSQLServer::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__G__PgSQL_116_0_26, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TPgSQLServer::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("TPgSQLServer", 1138, G__G__PgSQL_116_0_27, (int) ('i'), G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLServer), -1, 0, 1, 1, 1, 0, "u 'TPgSQLServer' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TPgSQLServer", 1264, G__G__PgSQL_116_0_28, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__G__PgSQL_116_0_29, (int) ('u'), G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLServer), -1, 1, 1, 1, 1, 0, "u 'TPgSQLServer' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncTPgSQLStatement(void) {
   /* TPgSQLStatement */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLStatement));
   G__memfunc_setup("IsSetParsMode",1283,(G__InterfaceMethod) NULL, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 4, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("IsResultSetMode",1516,(G__InterfaceMethod) NULL, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 4, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetSQLParamType",1455,(G__InterfaceMethod) NULL, 103, -1, G__defined_typename("Bool_t"), 0, 4, 1, 4, 0, 
"i - 'Int_t' 0 - npar i - - 0 - sqltype "
"g - - 0 - sig i - - 0 '0' sqlsize", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ConvertToNumeric",1655,(G__InterfaceMethod) NULL, 113, -1, -1, 0, 1, 1, 4, 0, "i - 'Int_t' 0 - npar", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ConvertToString",1563,(G__InterfaceMethod) NULL, 67, -1, -1, 0, 1, 1, 4, 1, "i - 'Int_t' 0 - npar", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FreeBuffers",1103,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetBuffersNumber",1634,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 0, "i - 'Int_t' 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TPgSQLStatement",1456,G__G__PgSQL_119_0_8, 105, G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLStatement), -1, 0, 2, 1, 1, 0, 
"U 'PgSQL_Stmt_t' - 0 - stmt g - 'Bool_t' 0 'kTRUE' errout", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Close",502,G__G__PgSQL_119_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "C - 'Option_t' 10 '\"\"' -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetBufferLength",1500,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetNumParameters",1636,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetNull",711,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - npar", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetInt",599,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - npar i - 'Int_t' 0 - value", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetUInt",684,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - npar h - 'UInt_t' 0 - value", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetLong",700,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - npar l - 'Long_t' 0 - value", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetLong64",806,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - npar n - 'Long64_t' 0 - value", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetULong64",891,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - npar m - 'ULong64_t' 0 - value", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetDouble",903,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - npar d - 'Double_t' 0 - value", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetString",931,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 3, 1, 1, 0, 
"i - 'Int_t' 0 - npar C - - 10 - value "
"i - 'Int_t' 0 '256' maxsize", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetBinary",913,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 4, 1, 1, 0, 
"i - 'Int_t' 0 - npar Y - - 0 - mem "
"l - 'Long_t' 0 - size l - 'Long_t' 0 '0x1000' maxsize", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetDate",682,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 4, 1, 1, 0, 
"i - 'Int_t' 0 - npar i - 'Int_t' 0 - year "
"i - 'Int_t' 0 - month i - 'Int_t' 0 - day", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetTime",699,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 4, 1, 1, 0, 
"i - 'Int_t' 0 - npar i - 'Int_t' 0 - hour "
"i - 'Int_t' 0 - min i - 'Int_t' 0 - sec", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetDatime",896,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 7, 1, 1, 0, 
"i - 'Int_t' 0 - npar i - 'Int_t' 0 - year "
"i - 'Int_t' 0 - month i - 'Int_t' 0 - day "
"i - 'Int_t' 0 - hour i - 'Int_t' 0 - min "
"i - 'Int_t' 0 - sec", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("SetTimestamp",1248,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 8, 1, 1, 0, 
"i - 'Int_t' 0 - npar i - 'Int_t' 0 - year "
"i - 'Int_t' 0 - month i - 'Int_t' 0 - day "
"i - 'Int_t' 0 - hour i - 'Int_t' 0 - min "
"i - 'Int_t' 0 - sec i - 'Int_t' 0 '0' frac", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("NextIteration",1358,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Process",735,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetNumAffectedRows",1805,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StoreResult",1164,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetNumFields",1191,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetFieldName",1157,(G__InterfaceMethod) NULL,67, -1, -1, 0, 1, 1, 1, 1, "i - 'Int_t' 0 - nfield", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("NextResultRow",1366,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("IsNull",599,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - npar", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetInt",587,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - npar", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetUInt",672,(G__InterfaceMethod) NULL,104, -1, G__defined_typename("UInt_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - npar", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetLong",688,(G__InterfaceMethod) NULL,108, -1, G__defined_typename("Long_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - npar", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetLong64",794,(G__InterfaceMethod) NULL,110, -1, G__defined_typename("Long64_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - npar", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetULong64",879,(G__InterfaceMethod) NULL,109, -1, G__defined_typename("ULong64_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - npar", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetDouble",891,(G__InterfaceMethod) NULL,100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - npar", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetString",919,(G__InterfaceMethod) NULL,67, -1, -1, 0, 1, 1, 1, 1, "i - 'Int_t' 0 - npar", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetBinary",901,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 3, 1, 1, 0, 
"i - 'Int_t' 0 - npar Y - - 1 - mem "
"l - 'Long_t' 1 - size", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetDate",670,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 4, 1, 1, 0, 
"i - 'Int_t' 0 - npar i - 'Int_t' 1 - year "
"i - 'Int_t' 1 - month i - 'Int_t' 1 - day", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetTime",687,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 4, 1, 1, 0, 
"i - 'Int_t' 0 - npar i - 'Int_t' 1 - hour "
"i - 'Int_t' 1 - min i - 'Int_t' 1 - sec", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetDatime",884,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 7, 1, 1, 0, 
"i - 'Int_t' 0 - npar i - 'Int_t' 1 - year "
"i - 'Int_t' 1 - month i - 'Int_t' 1 - day "
"i - 'Int_t' 1 - hour i - 'Int_t' 1 - min "
"i - 'Int_t' 1 - sec", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("GetTimestamp",1236,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 8, 1, 1, 0, 
"i - 'Int_t' 0 - npar i - 'Int_t' 1 - year "
"i - 'Int_t' 1 - month i - 'Int_t' 1 - day "
"i - 'Int_t' 1 - hour i - 'Int_t' 1 - min "
"i - 'Int_t' 1 - sec i - 'Int_t' 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__G__PgSQL_119_0_45, 85, G__get_linked_tagnum(&G__G__PgSQLLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TPgSQLStatement::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__G__PgSQL_119_0_46, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TPgSQLStatement::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__G__PgSQL_119_0_47, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TPgSQLStatement::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__G__PgSQL_119_0_48, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TPgSQLStatement::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__G__PgSQLLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__G__PgSQL_119_0_52, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__G__PgSQL_119_0_53, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TPgSQLStatement::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__G__PgSQL_119_0_54, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TPgSQLStatement::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__G__PgSQL_119_0_55, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TPgSQLStatement::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__G__PgSQL_119_0_56, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TPgSQLStatement::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("TPgSQLStatement", 1456, G__G__PgSQL_119_0_57, (int) ('i'), G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLStatement), -1, 0, 1, 1, 1, 0, "u 'TPgSQLStatement' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TPgSQLStatement", 1582, G__G__PgSQL_119_0_58, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__G__PgSQL_119_0_59, (int) ('u'), G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLStatement), -1, 1, 1, 1, 1, 0, "u 'TPgSQLStatement' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncG__PgSQL() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalG__PgSQL() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcG__PgSQL() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__G__PgSQLLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__G__PgSQLLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__G__PgSQLLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__G__PgSQLLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__G__PgSQLLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__G__PgSQLLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__G__PgSQLLN_TSQLRow = { "TSQLRow" , 99 , -1 };
G__linked_taginfo G__G__PgSQLLN_TSQLResult = { "TSQLResult" , 99 , -1 };
G__linked_taginfo G__G__PgSQLLN_PGresult = { "PGresult" , 115 , -1 };
G__linked_taginfo G__G__PgSQLLN_TPgSQLResult = { "TPgSQLResult" , 99 , -1 };
G__linked_taginfo G__G__PgSQLLN_TPgSQLRow = { "TPgSQLRow" , 99 , -1 };
G__linked_taginfo G__G__PgSQLLN_TSQLStatement = { "TSQLStatement" , 99 , -1 };
G__linked_taginfo G__G__PgSQLLN_TSQLServer = { "TSQLServer" , 99 , -1 };
G__linked_taginfo G__G__PgSQLLN_PGconn = { "PGconn" , 115 , -1 };
G__linked_taginfo G__G__PgSQLLN_TPgSQLServer = { "TPgSQLServer" , 99 , -1 };
G__linked_taginfo G__G__PgSQLLN_PgSQL_Stmt_t = { "PgSQL_Stmt_t" , 115 , -1 };
G__linked_taginfo G__G__PgSQLLN_TPgSQLStatement = { "TPgSQLStatement" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableG__PgSQL() {
  G__G__PgSQLLN_TClass.tagnum = -1 ;
  G__G__PgSQLLN_TBuffer.tagnum = -1 ;
  G__G__PgSQLLN_TMemberInspector.tagnum = -1 ;
  G__G__PgSQLLN_TObject.tagnum = -1 ;
  G__G__PgSQLLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__G__PgSQLLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__G__PgSQLLN_TSQLRow.tagnum = -1 ;
  G__G__PgSQLLN_TSQLResult.tagnum = -1 ;
  G__G__PgSQLLN_PGresult.tagnum = -1 ;
  G__G__PgSQLLN_TPgSQLResult.tagnum = -1 ;
  G__G__PgSQLLN_TPgSQLRow.tagnum = -1 ;
  G__G__PgSQLLN_TSQLStatement.tagnum = -1 ;
  G__G__PgSQLLN_TSQLServer.tagnum = -1 ;
  G__G__PgSQLLN_PGconn.tagnum = -1 ;
  G__G__PgSQLLN_TPgSQLServer.tagnum = -1 ;
  G__G__PgSQLLN_PgSQL_Stmt_t.tagnum = -1 ;
  G__G__PgSQLLN_TPgSQLStatement.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableG__PgSQL() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__G__PgSQLLN_TClass);
   G__get_linked_tagnum_fwd(&G__G__PgSQLLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__G__PgSQLLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__G__PgSQLLN_TObject);
   G__get_linked_tagnum_fwd(&G__G__PgSQLLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__G__PgSQLLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__G__PgSQLLN_TSQLRow);
   G__get_linked_tagnum_fwd(&G__G__PgSQLLN_TSQLResult);
   G__get_linked_tagnum_fwd(&G__G__PgSQLLN_PGresult);
   G__tagtable_setup(G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLResult),sizeof(TPgSQLResult),-1,62464,"PgSQL query result",G__setup_memvarTPgSQLResult,G__setup_memfuncTPgSQLResult);
   G__tagtable_setup(G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLRow),sizeof(TPgSQLRow),-1,62464,"One row of PgSQL query result",G__setup_memvarTPgSQLRow,G__setup_memfuncTPgSQLRow);
   G__get_linked_tagnum_fwd(&G__G__PgSQLLN_TSQLStatement);
   G__get_linked_tagnum_fwd(&G__G__PgSQLLN_TSQLServer);
   G__get_linked_tagnum_fwd(&G__G__PgSQLLN_PGconn);
   G__tagtable_setup(G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLServer),sizeof(TPgSQLServer),-1,62464,"Connection to PgSQL server",G__setup_memvarTPgSQLServer,G__setup_memfuncTPgSQLServer);
   G__get_linked_tagnum_fwd(&G__G__PgSQLLN_PgSQL_Stmt_t);
   G__tagtable_setup(G__get_linked_tagnum(&G__G__PgSQLLN_TPgSQLStatement),sizeof(TPgSQLStatement),-1,62464,"SQL statement class for PgSQL DB",G__setup_memvarTPgSQLStatement,G__setup_memfuncTPgSQLStatement);
}
extern "C" void G__cpp_setupG__PgSQL(void) {
  G__check_setup_version(30051515,"G__cpp_setupG__PgSQL()");
  G__set_cpp_environmentG__PgSQL();
  G__cpp_setup_tagtableG__PgSQL();

  G__cpp_setup_inheritanceG__PgSQL();

  G__cpp_setup_typetableG__PgSQL();

  G__cpp_setup_memvarG__PgSQL();

  G__cpp_setup_memfuncG__PgSQL();
  G__cpp_setup_globalG__PgSQL();
  G__cpp_setup_funcG__PgSQL();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncG__PgSQL();
  return;
}
class G__cpp_setup_initG__PgSQL {
  public:
    G__cpp_setup_initG__PgSQL() { G__add_setup_func("G__PgSQL",(G__incsetup)(&G__cpp_setupG__PgSQL)); G__call_setup_funcs(); }
   ~G__cpp_setup_initG__PgSQL() { G__remove_setup_func("G__PgSQL"); }
};
G__cpp_setup_initG__PgSQL G__cpp_setup_initializerG__PgSQL;

