/********************************************************************
* sql/pgsql/src/G__PgSQL.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error sql/pgsql/src/G__PgSQL.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableG__PgSQL();
extern void G__cpp_setup_inheritanceG__PgSQL();
extern void G__cpp_setup_typetableG__PgSQL();
extern void G__cpp_setup_memvarG__PgSQL();
extern void G__cpp_setup_globalG__PgSQL();
extern void G__cpp_setup_memfuncG__PgSQL();
extern void G__cpp_setup_funcG__PgSQL();
extern void G__set_cpp_environmentG__PgSQL();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TPgSQLResult.h"
#include "TPgSQLRow.h"
#include "TPgSQLServer.h"
#include "TPgSQLStatement.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__PgSQLLN_TClass;
extern G__linked_taginfo G__G__PgSQLLN_TBuffer;
extern G__linked_taginfo G__G__PgSQLLN_TMemberInspector;
extern G__linked_taginfo G__G__PgSQLLN_TObject;
extern G__linked_taginfo G__G__PgSQLLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__PgSQLLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__PgSQLLN_TSQLRow;
extern G__linked_taginfo G__G__PgSQLLN_TSQLResult;
extern G__linked_taginfo G__G__PgSQLLN_PGresult;
extern G__linked_taginfo G__G__PgSQLLN_TPgSQLResult;
extern G__linked_taginfo G__G__PgSQLLN_TPgSQLRow;
extern G__linked_taginfo G__G__PgSQLLN_TSQLStatement;
extern G__linked_taginfo G__G__PgSQLLN_TSQLServer;
extern G__linked_taginfo G__G__PgSQLLN_PGconn;
extern G__linked_taginfo G__G__PgSQLLN_TPgSQLServer;
extern G__linked_taginfo G__G__PgSQLLN_PgSQL_Stmt_t;
extern G__linked_taginfo G__G__PgSQLLN_TPgSQLStatement;

/* STUB derived class for protected member access */
