#!/bin/sh 

export CRMROOT=`pwd`
cd cream

ls /data/RAW/BeamTest/cream8/beamtest/2015/aug31/*dat /data/RAW/BeamTest/cream8/beamtest/2015/aug31/*bsd.led > LIST
./adc

mv ROOT/*root /data/L0/beamtest/2015/aug31
