/********************************************************************
* sql/mysql/src/G__MySQL.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error sql/mysql/src/G__MySQL.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableG__MySQL();
extern void G__cpp_setup_inheritanceG__MySQL();
extern void G__cpp_setup_typetableG__MySQL();
extern void G__cpp_setup_memvarG__MySQL();
extern void G__cpp_setup_globalG__MySQL();
extern void G__cpp_setup_memfuncG__MySQL();
extern void G__cpp_setup_funcG__MySQL();
extern void G__set_cpp_environmentG__MySQL();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TMySQLResult.h"
#include "TMySQLRow.h"
#include "TMySQLServer.h"
#include "TMySQLStatement.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__G__MySQLLN_TClass;
extern G__linked_taginfo G__G__MySQLLN_TBuffer;
extern G__linked_taginfo G__G__MySQLLN_TMemberInspector;
extern G__linked_taginfo G__G__MySQLLN_TObject;
extern G__linked_taginfo G__G__MySQLLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__G__MySQLLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__G__MySQLLN_TList;
extern G__linked_taginfo G__G__MySQLLN_TString;
extern G__linked_taginfo G__G__MySQLLN_TSQLRow;
extern G__linked_taginfo G__G__MySQLLN_TSQLResult;
extern G__linked_taginfo G__G__MySQLLN_MYSQL_RES;
extern G__linked_taginfo G__G__MySQLLN_MYSQL_FIELD;
extern G__linked_taginfo G__G__MySQLLN_TMySQLResult;
extern G__linked_taginfo G__G__MySQLLN_TMySQLRow;
extern G__linked_taginfo G__G__MySQLLN_TSQLStatement;
extern G__linked_taginfo G__G__MySQLLN_TSQLTableInfo;
extern G__linked_taginfo G__G__MySQLLN_TSQLServer;
extern G__linked_taginfo G__G__MySQLLN_MYSQL;
extern G__linked_taginfo G__G__MySQLLN_TMySQLServer;
extern G__linked_taginfo G__G__MySQLLN_MYSQL_STMT;
extern G__linked_taginfo G__G__MySQLLN_MYSQL_BIND;
extern G__linked_taginfo G__G__MySQLLN_TMySQLStatement;
extern G__linked_taginfo G__G__MySQLLN_TMySQLStatementcLcLTParamData;

/* STUB derived class for protected member access */
