/* This is file is automatically generated */
#define BUILD_ARCH "linux"
#define BUILD_NODE "Linux ISS-CDPS4 2.6.32-504.12.2.el6.i686 #1 SMP Wed Mar 11 11:14:43 CDT 2015 i686 i686 i386 GNU/Linux" 
#define COMPILER "/usr/bin/g++" 
#define COMPILERVERS "gcc446"
#define MAKESHAREDLIB  "cd $BuildDir ; g++ -c $Opt -pipe -m32 -Wall -W -Woverloaded-virtual -fPIC -pthread $IncludePath $SourceFiles ;  g++ $ObjectFiles -shared -Wl,-soname,$LibName.so -m32 -O2  $DepLibs -o $SharedLib"
#define MAKEEXE "cd $BuildDir ; g++ -c  -pipe -m32 -Wall -W -Woverloaded-virtual -fPIC -pthread $IncludePath $SourceFiles; g++ $ObjectFiles -m32 -O2  -o $ExeName $LinkedLibs -lm -ldl  -pthread -rdynamic"
#define CXXOPT "-O2"
#define CXXDEBUG "-g"
#define ROOTBUILD ""
#define LINKEDLIBS "-L$ROOTSYS/lib -lCore -lCint -lMathCore -lRint "
#define INCLUDEPATH "-I$ROOTSYS/include"
#define OBJEXT "o" 
#define SOEXT "so" 
