# -*- mode: makefile -*-
#
# Makefile definitions included by the top Makefile

ARCH           := linux

USECONFIG      := FALSE
MKLIBOPTIONS   := 

EXTRA_CFLAGS   := -Iinclude 
EXTRA_CXXFLAGS := -Iinclude 
EXTRA_LDFLAGS  := 
WINRTDEBUG     := no
ENABLEPCH      := no
NOSTUBS        := no
NOSTUBSTEST    := no

GLBPATCHFLAGS  := 
EXTRA_AUTHFLAGS:=    -DR__SSL -DOPENSSL_NO_KRB5

BINDIR         := $(ROOTSYS)/bin
LIBDIR         := $(ROOTSYS)/lib
INCDIR         := $(ROOTSYS)/include
ETCDIR         := $(ROOTSYS)/etc
MANDIR         := $(ROOTSYS)/man/man1
DATADIR        := $(ROOTSYS)
ELISPDIR       := $(ROOTSYS)/build/misc
TTFFONTDIR     := $(ROOTSYS)/fonts
MACRODIR       := $(ROOTSYS)/macros
SRCDIR         := $(ROOTSYS)/src
ICONPATH       := $(ROOTSYS)/icons
CINTINCDIR     := $(ROOTSYS)/cint
DOCDIR         := $(ROOTSYS)
TESTDIR        := $(ROOTSYS)/test
TUTDIR         := $(ROOTSYS)/tutorials
ACLOCALDIR     := $(ROOTSYS)/build/misc

X11LIBDIR      := 
XPMLIBDIR      := 
XPMLIB         := -lXpm
XFTLIB         := yes

EXCEPTIONS     := yes
EXPLICITLINK   := no

ENABLETHREAD   := yes
OSTHREADFLAG   := -pthread
OSTHREADLIBDIR := 
OSTHREADLIB    := -pthread

BUILTINFREETYPE:= yes

BUILTINPCRE    := yes

BUILTINZLIB    := yes
ZLIBLIBDIR     := 
ZLIBCLILIB     := 
ZLIBINCDIR     := $(filter-out /usr/include, )

BUILDGL        := yes
OPENGLLIBDIR   := 
OPENGLULIB     := -lGLU
OPENGLLIB      := -lGL
OPENGLINCDIR   := $(filter-out /usr/include, /usr/include)

BUILDLDAP      := yes
LDAPLIBDIR     :=   
LDAPCLILIB     :=  -lldap -llber
LDAPINCDIR     := $(filter-out /usr/include, /usr/include)

BUILDMYSQL     := yes
MYSQLLIBDIR    := 
MYSQLCLILIB    := -rdynamic -L/usr/lib/mysql -lmysqlclient -lz -lcrypt -lnsl -lm -lssl -lcrypto
MYSQLINCDIR    := $(filter-out /usr/include, /usr/include/mysql)

BUILDORACLE    := no
ORACLELIBDIR   := 
ORACLECLILIB   :=  
ORACLEINCDIR   := $(filter-out /usr/include, )

BUILDPGSQL     := yes
PGSQLLIBDIR    := 
PGSQLCLILIB    := -lpq
PGSQLINCDIR    := $(filter-out /usr/include, /usr/include)

BUILDSAPDB     := no
SAPDBLIBDIR    := 
SAPDBCLILIB    := 
SAPDBINCDIR    := $(filter-out /usr/include, )

BUILDODBC      := no
ODBCLIBDIR     := 
ODBCCLILIB     := 
ODBCINCDIR     := $(filter-out /usr/include, )

BUILDQT        := no
BUILDQTGSI     := no
QTLIBDIR       := 
QTLIB          := 
QTINCDIR       := $(filter-out /usr/include, )
QTVERS	       := 
QTMOCEXE       := 

BUILDRFIO      := no
SHIFTLIBDIR    := 
SHIFTLIB       := 
SHIFTINCDIR    := $(filter-out /usr/include, )
SHIFTCFLAGS    := 

BUILDCASTOR    := no
CASTORLIBDIR   := 
CASTORCLILIB   := 
CASTORINCDIR   := $(filter-out /usr/include, )
CASTORCFLAGS   := 

BUILDDCAP      := no
DCAPLIBDIR     := 
DCAPLIB        := 
DCAPINCDIR     := $(filter-out /usr/include, )

BUILDFTGL      := yes
FTGLLIBDIR     := -Llib
FTGLLIBS       := -lFTGL
FTGLINCDIR     := $(filter-out /usr/include, include)
ifeq ($(BUILDFTGL), yes)
FTGLCPPFLAGS   := -DBUILTIN_FTGL
endif

BUILDGLEW      := yes
GLEWLIBDIR     := -Llib
GLEWLIBS       := -lGLEW
GLEWINCDIR     := $(filter-out /usr/include, include)
ifeq ($(BUILDGLEW), yes)
GLEWCPPFLAGS   := -DBUILTIN_GLEW
endif

BUILDGFAL      := no
GFALLIBDIR     := 
GFALCLILIB     := 
GFALINCDIR     := $(filter-out /usr/include, )

BUILDG4ROOT    := no
G4LIBDIR       := 
G4INCDIR       := $(filter-out /usr/include, )
CLHEPINCDIR    := $(filter-out /usr/include, )

BUILDGLITE     := no
GLITELIBDIR    := 
GAWLIB         := 
GAW_CPPFLAGS   := $(filter-out /usr/include, )

BUILDMEMSTAT   := yes

BUILDBONJOUR   := no
DNSSDLIBDIR    := 
DNSSDLIB       := 
DNSSDINCDIR    := $(filter-out /usr/include, )

BUILDCHIRP     := no
CHIRPLIBDIR    := 
CHIRPCLILIB    := 
CHIRPINCDIR    := $(filter-out /usr/include, )

BUILDHDFS     := no
HDFSLIBDIR    := 
HDFSCLILIB    := 
HDFSINCDIR    := $(filter-out /usr/include, )
JNIINCDIR     := $(filter-out /usr/include, ) $(filter-out /usr/include, /linux)
JVMCLILIB     := 
JVMLIBDIR     := 

BUILDALIEN     := no
ALIENLIBDIR    := 
ALIENCLILIB    := 
ALIENINCDIR    := $(filter-out /usr/include, )

BUILDASIMAGE   := yes
BUILTINASIMAGE := yes
ASEXTRALIB     :=  -ljpeg -ltiff -lpng -lz
ASEXTRALIBDIR  :=     
ASJPEGINCDIR   := $(filter-out /usr/include, /usr/include)
ASPNGINCDIR    := $(filter-out /usr/include, /usr/include)
ASTIFFINCDIR   := $(filter-out /usr/include, /usr/include)
ASGIFINCDIR    := $(filter-out /usr/include, )
ASINCDIR       := $(filter-out /usr/include, )
ASLIB          := 
ASLIBDIR       := 

BUILDFPYTHIA6    := no
FPYTHIA6LIBDIR   := 
FPYTHIA6LIB      := 
FPYTHIA6CPPFLAGS := 

BUILDFPYTHIA8    := no
FPYTHIA8INCDIR   := 
FPYTHIA8LIBDIR   := 
FPYTHIA8LIB      := 

BUILDFFTW3     := no
FFTW3LIBDIR    := 
FFTW3LIB       := 
FFTW3INCDIR    := $(filter-out /usr/include, )

BUILDGVIZ      := no
GRAPHVIZLIBDIR := 
GRAPHVIZLIB    := 
GRAPHVIZINCDIR := $(filter-out /usr/include, )
GRAPHVIZCFLAGS := 

BUILDPYTHON    := yes
PYTHONLIBDIR   := -L/usr/lib/python2.6/config
PYTHONLIB      := -lpython2.6
PYTHONINCDIR   := $(filter-out /usr/include, /usr/include/python2.6)
PYTHONLIBFLAGS := 

BUILDRUBY      := no
RUBYLIBDIR     := 
RUBYLIB        := 
RUBYINCDIR     := $(filter-out /usr/include, )

BUILDXML       := yes
XMLLIBDIR      := 
XMLCLILIB      := -lxml2 -lz -lm
XMLINCDIR      := $(filter-out /usr/include, /usr/include/libxml2)

BUILDXRD       := yes
XRDINCDIR      := 
XRDLIBDIR      := 
XRDADDOPTS     := 
EXTRA_XRDFLAGS := -DUSENEWHDRS

SRPLIBDIR      := 
SRPLIB         := 
SRPINCDIR      := $(filter-out /usr/include, )

BUILDSRPUTIL   := 
SRPUTILLIBDIR  := 
SRPUTILLIB     := 
SRPUTILINCDIR  := $(filter-out /usr/include, )

AFSLIB         := 
AFSLIBDIR      := 
AFSINCDIR      := 
AFSEXTRACFLAGS := 
AFSSHARED      := 

BUILDKRB5      := no
KRB5LIB        := 
KRB5LIBDIR     := 
KRB5INCDIR     := $(filter-out /usr/include, )
KRB5INIT       := 

COMERRLIB      := 
COMERRLIBDIR   := 

RESOLVLIB      := 

CRYPTOLIB      := 
CRYPTOLIBDIR   := 

BUILDGLOBUS    := no
GLOBUSLIB      := 
GLOBUSLIBDIR   := 
GLOBUSINCDIR   := $(filter-out /usr/include, )
BUILDXRDGSI    := yes

BUILDMONALISA  := no
MONALISALIBDIR := 
MONALISACLILIB := 
MONALISAINCDIR := $(filter-out /usr/include, )

SSLLIB         := -lssl -lcrypto
SSLLIBDIR      := 
SSLINCDIR      := $(filter-out /usr/include, /usr/include)
SSLSHARED      := yes

SHADOWFLAGS    := -DR__SHADOWPW 
SHADOWLIB      :=
SHADOWLIBDIR   :=

BUILDGENVECTOR := yes

BUILDMATHMORE  := no
GSLFLAGS       := $(filter-out -I/usr/include, )
GSLLIBDIR      := 
GSLLIBS        := 
GSLVERSION     := 

BUILDCINT5     := yes
BUILDCINT7     := 
ifeq ($(BUILDCINT5)_$(BUILDCINT7),yes_yes)
BUILDBOTHCINT  := yes
else
BUILDBOTHCINT  :=
endif

BUILDCINTEX    := yes

BUILDREFLEX    := yes

BUILDROOFIT    := 

BUILDMINUIT2   := 

BUILDUNURAN    := 

BUILDGDML      := 

BUILDTABLE     := 

BUILDTMVA      := yes

BUILDCLARENS   := no
CLARENSINC     := $(filter-out -I/usr/include, )
CLARENSLIBS    := 

BUILDPEAC      := no

CURSESINCDIR   := $(filter-out -I/usr/include, -I/usr/include/ncurses)
CURSESLIBDIR   := 
CURSESHDR      := ncurses.h
CURSESLIB      := -lncurses
BUILDEDITLINE  := yes

CPPUNIT        := 
GCCXML         := 

ROOTDICTTYPE   := cint

INSTALL        := cp -dpR
INSTALLDATA    := cp -dpR
INSTALLDIR     := mkdir -p

ROOTDRPMREL    := 1
